### PR TITLE
Initial updating

### PR DESCRIPTION
**Pull request by taubenangriff**
REMOVED: 
Influence reduced for ships
Southern Rivers Reduced

---

Harborlife
- added harbor samba school, harbor cinema, harbor artista residences

Influence rebalancing
- fixed airship costs
- added tweaks

Large Tourism Ship
- fixed the mod. You can only build new ships. old are lost

City ornaments, Clay Covers, Construction Sites, Plaza Decorations, Trees with fences, Worker Ornaments, World Fair Items
- moved to ornaments tab

### CODE REVIEW

**Comment by D3nnis3n** [comment]
Isn't the DLC only making riverless isles more common? Would still be great to have guaranteed no river isles.

Also thanks for your mod collection and all the work invested into it, Anno is so much more fun with it :)

**Comment by Taskmage42** [comment]
Looking at the diff, Southern Rivers Reduced got removed, Southern Rivers Removed is still in. The Reduced variant did add the island variants without rivers to the map generation pool, that is no longer needed since they (should) now be used by default. So probably the comment is just a bit off.

**Comment by taubenangriff** [comment]
Exactly, southern rivers removed will stay but it needs edits.

Southern rivers reduced will get nuked.

**Comment by D3nnis3n** [comment]
Ah sorry, the mobile Github seems pretty bugged, I had a look at commit, but looked like its gone :D

**Pull request merged**
